before:
  hooks:
  - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
release:
  github:
    owner: soupdiver
    name: goreleaser
  prerelease: auto

